[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "serve dist -p 8080 -l 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
