import {
  Percent,
  Calculator,
  FunctionSquare,
  AreaChart,
  Divide,
  Sigma,
  GitCommitHorizontal,
  Triangle,
  Circle,
  Ruler,
  Box,
  Binary,
  Lightbulb
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const MATH_CALCULATORS_DATA = {
    "title": "Math Calculators",
    "count": 970,
    "description": "Math can be exciting and easier than you think! With our collection of maths calculators, everyone can perform and understand useful mathematical calculations in seconds. Are you scared of trigonometry? Do you think geometry is “too complicated”? Fear not! Omni Calculator has your back, with a comprehensive array of calculators designed so that people with any level of mathematical knowledge can solve complex problems effortlessly. From our algebra calculators, through plenty percentage calculators to our trigonometry calculators, we’ve got everything you need. Whether you need a fraction calculator to simplify ratios or a square root calculator to check your homework... You name it, we have it! In addition to the top-notch mathematical calculators, we include accurate yet straightforward descriptions of mathematical concepts to shine some light on the complex problems you never seemed to understand.",
    "subcategories": [
        {
            "title": "Percentages calculators",
            "icon": Percent,
            "calculators": [
                { "name": "Average Percentage Calculator", "href": "/calculators/math/average-percentage-calculator" },
                { "name": "Fraction to Percent Calculator", "href": "#" },
                { "name": "Decimal to Percent Converter", "href": "#" },
                { "name": "Doubling Time Calculator", "href": "#" },
                { "name": "Percentage Calculator", "href": "#" },
                { "name": "Percentage Change Calculator", "href": "#" },
                { "name": "Percentage Decrease Calculator", "href": "#" },
                { "name": "Percentage Difference Calculator", "href": "#" },
                { "name": "Percentage Increase Calculator", "href": "#" },
                { "name": "Percentage Increase Classic", "href": "#" },
                { "name": "Percentage of a Percentage Calculator", "href": "#" },
                { "name": "Percentage Point Calculator", "href": "#" },
                { "name": "Percent Error Calculator", "href": "#" },
                { "name": "Time Percentage Calculator", "href": "#" },
                { "name": "Percent to Goal Calculator", "href": "#" },
                { "name": "Relative Change Calculator", "href": "#" },
                { "name": "Slope Percentage Calculator", "href": "#" }
            ]
        },
        {
            "title": "Algebra calculators",
            "icon": Calculator,
            "calculators": [
                { "name": "Absolute Value Equation Calculator", "href": "#" },
                { "name": "Absolute Value Inequalities Calculator", "href": "#" },
                { "name": "Adding and Subtracting Polynomials Calculator", "href": "#" },
                { "name": "Bessel Function Calculator", "href": "#" },
                { "name": "Binomial Coefficient Calculator", "href": "#" },
                { "name": "Box Method Calculator", "href": "#" },
                { "name": "Completing the Square Calculator", "href": "#" },
                { "name": "Complex Conjugate Calculator", "href": "#" },
                { "name": "Complex Number Calculator", "href": "#" },
                { "name": "Complex Root Calculator", "href": "#" },
                { "name": "Cubic Equation Calculator", "href": "#" },
                { "name": "Descartes' Rule of Signs Calculator", "href": "#" },
                { "name": "Diamond Problem Calculator", "href": "#" },
                { "name": "Direct Variation Calculator", "href": "#" },
                { "name": "Discriminant Calculator", "href": "#" },
                { "name": "Elimination Method Calculator", "href": "#" },
                { "name": "Error Function Calculator", "href": "#" },
                { "name": "Factoring Trinomials Calculator", "href": "#" },
                { "name": "FOIL Calculator", "href": "#" },
                { "name": "Gamma Function Calculator", "href": "#" },
                { "name": "Generic Rectangle Calculator", "href": "#" },
                { "name": "Graphing Inequalities on a Number Line Calculator", "href": "#" },
                { "name": "Graphing Quadratic Inequalities Calculator", "href": "#" },
                { "name": "Hyperbolic Functions Calculator", "href": "#" },
                { "name": "Inequality to Interval Notation Calculator", "href": "#" },
                { "name": "Interval Notation Calculator", "href": "#" },
                { "name": "Inverse Variation Calculator", "href": "#" },
                { "name": "Multiplying Binomials Calculator", "href": "#" },
                { "name": "Multiplying Polynomials Calculator", "href": "#" },
                { "name": "Partial Fraction Decomposition Calculator", "href": "#" },
                { "name": "Perfect Square Trinomial Calculator", "href": "#" },
                { "name": "Polynomial Division Calculator", "href": "#" },
                { "name": "Power Set Calculator", "href": "#" },
                { "name": "Quadratic Formula Calculator", "href": "#" },
                { "name": "Quaternion Calculator", "href": "#" },
                { "name": "Rational Zeros Calculator", "href": "#" },
                { "name": "Square of a Binomial Calculator", "href": "#" },
                { "name": "Subset Calculator", "href": "#" },
                { "name": "Substitution Method Calculator", "href": "#" },
                { "name": "Synthetic Division Calculator", "href": "#" },
                { "name": "System of Equations Calculator", "href": "#" },
                { "name": "Union and Intersection Calculator", "href": "#" }
            ]
        },
        {
            "title": "Arithmetic calculators",
            "icon": Divide,
            "calculators": [
                { "name": "Absolute Change Calculator", "href": "#" },
                { "name": "Absolute Value Calculator", "href": "#" },
                { "name": "Adding and Subtracting Fractions Calculator", "href": "#" },
                { "name": "Addition Calculator", "href": "#" },
                { "name": "Associative Property Calculator", "href": "#" },
                { "name": "Average Calculator", "href": "#" },
                { "name": "Ceiling Function Calculator", "href": "#" },
                { "name": "Chinese Remainder Theorem Calculator", "href": "#" },
                { "name": "Compatible Numbers Calculator", "href": "#" },
                { "name": "Consecutive Integers Calculator", "href": "#" },
                { "name": "Cross Multiplication Calculator", "href": "#" },
                { "name": "Cube Root Calculator", "href": "#" },
                { "name": "Decimal Calculator", "href": "#" },
                { "name": "Digital Root Calculator", "href": "#" },
                { "name": "Distributive Property Calculator", "href": "#" },
                { "name": "Divisibility Test Calculator", "href": "#" },
                { "name": "Egyptian Fractions Calculator", "href": "#" },
                { "name": "Expanded Form Calculator", "href": "#" },
                { "name": "Factor Calculator", "href": "#" },
                { "name": "Factorial Calculator", "href": "#" },
                { "name": "Fermat's Little Theorem Calculator", "href": "#" },
                { "name": "Floor Division Calculator", "href": "#" },
                { "name": "Floor Function Calculator", "href": "#" },
                { "name": "Fundamental Counting Principle Calculator", "href": "#" },
                { "name": "GCF Calculator – Greatest Common Factor", "href": "#" },
                { "name": "GCF and LCM Calculator", "href": "#" },
                { "name": "Geometric Mean Calculator", "href": "#" },
                { "name": "Greater Than Or Less Than Calculator", "href": "#" },
                { "name": "Harmonic Mean Calculator", "href": "#" },
                { "name": "Integer Calculator", "href": "#" },
                { "name": "Inverse Modulo Calculator", "href": "#" },
                { "name": "LCM Calculator — Least Common Multiple", "href": "#" },
                { "name": "Long Addition Calculator", "href": "#" },
                { "name": "Long Division Calculator", "href": "#" },
                { "name": "Long Multiplication Calculator", "href": "#" },
                { "name": "Long Subtraction Calculator", "href": "#" },
                { "name": "Magic Square Calculator", "href": "#" },
                { "name": "Mean Calculator", "href": "#" },
                { "name": "Modulo Calculator", "href": "#" },
                { "name": "Multiplication Calculator", "href": "#" },
                { "name": "Multiplicative Inverse Calculator", "href": "#" },
                { "name": "Multiplicative Inverse Modulo Calculator", "href": "#" },
                { "name": "Order of Magnitude Calculator", "href": "#" },
                { "name": "Partial Products Calculator", "href": "#" },
                { "name": "Perfect Cube Calculator", "href": "#" },
                { "name": "Perfect Square Calculator", "href": "#" },
                { "name": "Pi Experiments Calculator", "href": "#" },
                { "name": "Place Value Calculator", "href": "#" },
                { "name": "Polish Notation Converter", "href": "#" },
                { "name": "Power Mod Calculator", "href": "#" },
                { "name": "Powers of i Calculator", "href": "#" },
                { "name": "Prime Factorization Calculator", "href": "#" },
                { "name": "Prime Number Calculator", "href": "#" },
                { "name": "Quotient Calculator", "href": "#" },
                { "name": "Radical Calculator", "href": "#" },
                { "name": "Rationalize Denominator Calculator", "href": "#" },
                { "name": "Reciprocal Calculator", "href": "#" },
                { "name": "Relatively Prime Calculator", "href": "#" },
                { "name": "Remainder Calculator", "href": "#" },
                { "name": "Reverse FOIL Calculator", "href": "#" },
                { "name": "Root Calculator", "href": "#" },
                { "name": "Root Mean Square Calculator", "href": "#" },
                { "name": "Rounding Calculator", "href": "#" },
                { "name": "Round to the Nearest Thousand Calculator", "href": "#" },
                { "name": "Scientific Notation Calculator", "href": "#" },
                { "name": "Set Builder Calculator", "href": "#" },
                { "name": "Significant Figures Calculator – Sig Fig", "href": "#" },
                { "name": "Simplifying Radicals Calculator", "href": "#" },
                { "name": "Square Root Calculator", "href": "#" },
                { "name": "Standard Form Calculator", "href": "#" },
                { "name": "Subtracting Fractions Calculator", "href": "#" },
                { "name": "Subtraction Calculator", "href": "#" },
                { "name": "Digit Sum Calculator", "href": "#" },
                { "name": "Sum of Products Calculator", "href": "#" },
                { "name": "Terminating Decimals Calculator", "href": "#" },
                { "name": "Triangular Numbers Calculator", "href": "#" },
                { "name": "Weighted Average Calculator", "href": "#" }
            ]
        },
        {
            "title": "Coordinate geometry calculators",
            "icon": AreaChart,
            "calculators": [
                { "name": "Average Rate of Change Calculator", "href": "#" },
                { "name": "Bilinear Interpolation Calculator", "href": "#" },
                { "name": "Catenary Curve Calculator", "href": "#" },
                { "name": "Coordinate Grid Calculator", "href": "#" },
                { "name": "Cosine Similarity Calculator", "href": "#" },
                { "name": "Cross Product Calculator", "href": "#" },
                { "name": "Cylindrical Coordinates Calculator", "href": "#" },
                { "name": "Direction of the Vector Calculator", "href": "#" },
                { "name": "Distance Formula Calculator", "href": "#" },
                { "name": "Distance from Point to Plane Calculator", "href": "#" },
                { "name": "Dot Product Calculator", "href": "#" },
                { "name": "Endpoint Calculator", "href": "#" },
                { "name": "Equation of a Sphere Calculator", "href": "#" },
                { "name": "Gradient Calculator", "href": "#" },
                { "name": "Intersection of Two Lines Calculator", "href": "#" },
                { "name": "Irregular Polygon Area Calculator", "href": "#" },
                { "name": "Latus Rectum Calculator", "href": "#" },
                { "name": "Least Squares Regression Line Calculator", "href": "#" },
                { "name": "Linear Interpolation Calculator", "href": "#" },
                { "name": "Line Equation from Two Points Calculator", "href": "#" },
                { "name": "Line of Intersection of Two Planes Calculator", "href": "#" },
                { "name": "Manhattan Distance Calculator", "href": "#" },
                { "name": "Midpoint Calculator", "href": "#" },
                { "name": "Parabola Calculator", "href": "#" },
                { "name": "Parallel Line Calculator", "href": "#" },
                { "name": "Perpendicular Line Calculator", "href": "#" },
                { "name": "Point Slope Form Calculator", "href": "#" },
                { "name": "Polar Coordinates Calculator", "href": "#" },
                { "name": "Polynomial Graphing Calculator", "href": "#" },
                { "name": "Ratios of Directed Line Segments Calculator", "href": "#" },
                { "name": "Rise Over Run Calculator", "href": "#" },
                { "name": "Rotation Calculator", "href": "#" },
                { "name": "Scatter Plot Calculator", "href": "#" },
                { "name": "Slope Calculator", "href": "#" },
                { "name": "Slope Intercept Form Calculator", "href": "#" },
                { "name": "Spherical Coordinates Calculator", "href": "#" },
                { "name": "Standard Form to Slope Intercept Form Calculator", "href": "#" },
                { "name": "Three-Dimensional Distance Calculator", "href": "#" },
                { "name": "Triangulation Calculator", "href": "#" },
                { "name": "Unit Vector Calculator", "href": "#" },
                { "name": "Vector Calculator", "href": "#" },
                { "name": "Vector Addition Calculator", "href": "#" },
                { "name": "Vector Magnitude Calculator", "href": "#" },
                { "name": "Vector Projection Calculator", "href": "#" },
                { "name": "Vertex Form Calculator", "href": "#" },
                { "name": "Volume of a Parallelepiped Calculator", "href": "#" },
                { "name": "y Intercept Calculator", "href": "#" }
            ]
        },
        {
            "title": "Fractions calculators",
            "icon": Sigma,
            "calculators": [
                { "name": "Adding Fractions Calculator", "href": "#" },
                { "name": "Comparing Fractions Calculator", "href": "#" },
                { "name": "Decimal to Fraction Calculator", "href": "#" },
                { "name": "Dividing Fractions Calculator", "href": "#" },
                { "name": "Equivalent Fractions Calculator", "href": "#" },
                { "name": "Fraction Calculator", "href": "#" },
                { "name": "Fraction Exponent Calculator", "href": "#" },
                { "name": "Fraction To Decimal Converter", "href": "#" },
                { "name": "Golden Ratio Calculator", "href": "#" },
                { "name": "Improper Fraction to Mixed Number Calculator", "href": "#" },
                { "name": "LCD Calculator - Least Common Denominator", "href": "#" },
                { "name": "Lowest Term Calculator", "href": "#" },
                { "name": "Mixed Number Calculator", "href": "#" },
                { "name": "Mixed Number to Improper Fraction Calculator", "href": "#" },
                { "name": "Multiplying Fractions Calculator", "href": "#" },
                { "name": "Proportion Calculator", "href": "#" },
                { "name": "Ratio Calculator", "href": "#" },
                { "name": "Simplify Fractions Calculator", "href": "#" },
                { "name": "Unit Rate Calculator", "href": "#" }
            ]
        },
        {
            "title": "Linear algebra calculators",
            "icon": FunctionSquare,
            "calculators": [
                { "name": "Adjoint Matrix Calculator", "href": "#" },
                { "name": "Characteristic Polynomial Calculator", "href": "#" },
                { "name": "Cholesky Decomposition Calculator", "href": "#" },
                { "name": "Cofactor Expansion Calculator", "href": "#" },
                { "name": "Cofactor Matrix Calculator", "href": "#" },
                { "name": "Column Space Calculator", "href": "#" },
                { "name": "Condition Number Calculator", "href": "#" },
                { "name": "Corner Point Calculator", "href": "#" },
                { "name": "Cramer's Rule Calculator", "href": "#" },
                { "name": "Diagonalize Matrix Calculator", "href": "#" },
                { "name": "Eigenvalue and Eigenvector Calculator", "href": "#" },
                { "name": "Gauss-Jordan Elimination Calculator", "href": "#" },
                { "name": "Gram-Schmidt Calculator", "href": "#" },
                { "name": "Hadamard Product Calculator", "href": "#" },
                { "name": "Inverse Matrix Calculator", "href": "#" },
                { "name": "Linear Combination Calculator", "href": "#" },
                { "name": "Linear Independence Calculator", "href": "#" },
                { "name": "LU Decomposition Calculator", "href": "#" },
                { "name": "Matrix Calculator", "href": "#" },
                { "name": "Matrix Addition and Subtraction Calculator", "href": "#" },
                { "name": "Matrix by Scalar Calculator", "href": "#" },
                { "name": "Matrix Determinant Calculator", "href": "#" },
                { "name": "Matrix Multiplication Calculator", "href": "#" },
                { "name": "Matrix Norm Calculator", "href": "#" },
                { "name": "Matrix Power Calculator", "href": "#" },
                { "name": "Matrix Rank Calculator", "href": "#" },
                { "name": "Matrix Trace Calculator", "href": "#" },
                { "name": "Matrix Transpose Calculator", "href": "#" },
                { "name": "Null Space Calculator", "href": "#" },
                { "name": "Polar Decomposition Calculator", "href": "#" },
                { "name": "Pseudoinverse Calculator", "href": "#" },
                { "name": "QR Decomposition Calculator", "href": "#" },
                { "name": "(Reduced) Row Echelon Form Calculator", "href": "#" },
                { "name": "Singular Values Calculator", "href": "#" },
                { "name": "SVD Calculator", "href": "#" },
                { "name": "Tensor Product Calculator", "href": "#" }
            ]
        },
        {
            "title": "Trigonometry calculators",
            "icon": Triangle,
            "calculators": [
                { "name": "Arccos Calculator (Inverse Cosine)", "href": "#" },
                { "name": "Arcsin Calculator (Inverse Sine)", "href": "#" },
                { "name": "Arctan Calculator (Inverse Tangent)", "href": "#" },
                { "name": "Cofunction Calculator", "href": "#" },
                { "name": "Cosecant Calculator", "href": "#" },
                { "name": "Cosine Calculator", "href": "#" },
                { "name": "Cotangent Calculator", "href": "#" },
                { "name": "Double Angle Formula Calculator", "href": "#" },
                { "name": "Half Angle Calculator", "href": "#" },
                { "name": "Inverse Trigonometric Functions Calculator", "href": "#" },
                { "name": "Law of Cosines Calculator", "href": "#" },
                { "name": "Law of Sines Calculator", "href": "#" },
                { "name": "Phase Shift Calculator", "href": "#" },
                { "name": "Power Reducing Calculator", "href": "#" },
                { "name": "Secant Calculator", "href": "#" },
                { "name": "Sine Calculator", "href": "#" },
                { "name": "Sum and Difference Identities Calculator", "href": "#" },
                { "name": "Tangent Calculator", "href": "#" },
                { "name": "Trig Identities Calculator", "href": "#" },
                { "name": "Trigonometric Functions Calculator", "href": "#" },
                { "name": "Trigonometry Calculator", "href": "#" },
                { "name": "Unit Circle Calculator", "href": "#" }
            ]
        },
        {
            "title": "2D geometry calculators",
            "icon": Triangle,
            "calculators": [
                { "name": "Area Calculator", "href": "#" },
                { "name": "Area of a Rectangle Calculator", "href": "#" },
                { "name": "Area of Crescent Calculator", "href": "#" },
                { "name": "Center of Mass Calculator", "href": "#" },
                { "name": "Centroid Calculator", "href": "#" },
                { "name": "Chord Length Calculator", "href": "#" },
                { "name": "Conic Sections Calculator", "href": "#" },
                { "name": "Cross-Sectional Area Calculator", "href": "#" },
                { "name": "Cycloid Calculator", "href": "#" },
                { "name": "Ellipse Calculator", "href": "#" },
                { "name": "Golden Rectangle Calculator", "href": "#" },
                { "name": "Hexagon Calculator", "href": "#" },
                { "name": "Moment of Inertia Calculator", "href": "#" },
                { "name": "Octagon Calculator", "href": "#" },
                { "name": "Orthocenter Calculator", "href": "#" },
                { "name": "Pentagon Calculator", "href": "#" },
                { "name": "Perimeter Calculator", "href": "#" },
                { "name": "Quadrilateral Calculator", "href": "#" },
                { "name": "Polygon Calculator", "href": "#" },
                { "name": "Segment Addition Postulate Calculator", "href": "#" },
                { "name": "Segment Area Calculator", "href": "#" },
                { "name": "Spiral Length Calculator", "href": "#" },
                { "name": "Square Calc: find A, P, d", "href": "#" },
                { "name": "Star Shape Calculator", "href": "#" },
                { "name": "Trapezoid Calculator", "href": "#" }
            ]
        },
        {
            "title": "Triangle calculators",
            "icon": Triangle,
            "calculators": [
                { "name": "30 60 90 Triangle Calculator", "href": "#" },
                { "name": "45 45 90 Triangle Calculator", "href": "#" },
                { "name": "Area of a Right Triangle Calculator", "href": "#" },
                { "name": "Circumscribed Circle Calculator", "href": "#" },
                { "name": "Classifying Triangles Calculator", "href": "#" },
                { "name": "Equilateral Triangle Calculator", "href": "#" },
                { "name": "Heron's Formula Calculator", "href": "#" },
                { "name": "Hypotenuse Calculator", "href": "#" },
                { "name": "Isosceles Triangle Calculator", "href": "#" },
                { "name": "Perimeter of a Triangle Calculator", "href": "#" },
                { "name": "Pythagorean Theorem Calculator", "href": "#" },
                { "name": "Pythagorean Triples Calculator", "href": "#" },
                { "name": "Right Triangle Calculator", "href": "#" },
                { "name": "Right Triangle Side and Angle Calculator", "href": "#" },
                { "name": "Similar Triangles Calculator", "href": "#" },
                { "name": "Special Right Triangles Calculator", "href": "#" },
                { "name": "Triangle Angle Calculator", "href": "#" },
                { "name": "Triangle Area Calculator", "href": "#" },
                { "name": "Triangle Height Calculator", "href": "#" },
                { "name": "Triangle Inequality Theorem Calculator", "href": "#" }
            ]
        },
        {
            "title": "Circle calculators",
            "icon": Circle,
            "calculators": [
                { "name": "Arc Length Calculator", "href": "#" },
                { "name": "Area of a Circle Calculator", "href": "#" },
                { "name": "Circle Calculator", "href": "#" },
                { "name": "Circle Theorems Calculator", "href": "#" },
                { "name": "Circumference Calculator", "href": "#" },
                { "name": "Coin Rotation Paradox", "href": "#" },
                { "name": "Equation of a Circle Calculator", "href": "#" },
                { "name": "Sector Area Calculator", "href": "#" },
                { "name": "Semicircle Area Calculator", "href": "#" },
                { "name": "Square in a Circle Calculator", "href": "#" },
                { "name": "String Girdling Earth Calculator", "href": "#" },
                { "name": "Tangent of a Circle Calculator", "href": "#" }
            ]
        },
        {
            "title": "Angle calculators",
            "icon": Ruler,
            "calculators": [
                { "name": "Angle Between Two Vectors Calculator", "href": "#" },
                { "name": "Central Angle Calculator", "href": "#" },
                { "name": "Clock Angle Calculator", "href": "#" },
                { "name": "Complementary Angles Calculator", "href": "#" },
                { "name": "Coterminal Angle Calculator", "href": "#" },
                { "name": "Reference Angle Calculator", "href": "#" },
                { "name": "Supplementary Angles Calculator", "href": "#" }
            ]
        },
        {
            "title": "3D geometry calculators",
            "icon": Box,
            "calculators": [
                { "name": "Surface Area of a Hemisphere Calculator", "href": "#" },
                { "name": "Cube Calculator", "href": "#" },
                { "name": "Cube Calc: find V, a, d", "href": "#" },
                { "name": "Ellipsoid Volume Calculator", "href": "#" },
                { "name": "Great Circle Calculator", "href": "#" },
                { "name": "Lateral Area Trapezoidal Prism Calculator", "href": "#" },
                { "name": "Pyramid Angle Calculator", "href": "#" },
                { "name": "Pyramid Volume Calculator", "href": "#" },
                { "name": "Rectangular Prism Calculator", "href": "#" },
                { "name": "Right Circular Cone Calc: find A, V, A_L, A_B.", "href": "#" },
                { "name": "Right Cylinder Calculator: find A, V, A_l, A_b", "href": "#" },
                { "name": "Right Rectangular Pyramid Calc: find A, V, A_l, A_b", "href": "#" },
                { "name": "Slant Height calculator", "href": "#" },
                { "name": "Sphere Calc: find V, A, d", "href": "#" },
                { "name": "Surface Area Calculator", "href": "#" },
                { "name": "Surface Area of a Triangular Prism Calculator", "href": "#" },
                { "name": "Surface Area to Volume Ratio Calculator", "href": "#" },
                { "name": "Tetrahedron Volume Calculator", "href": "#" },
                { "name": "Torus Surface Area Calculator", "href": "#" },
                { "name": "Torus Volume Calculator", "href": "#" },
                { "name": "Triangular Prism Calculator", "href": "#" },
                { "name": "Volume Calculator", "href": "#" },
                { "name": "Volume of a Hemisphere Calculator", "href": "#" },
                { "name": "Volume of a Trapezoidal Prism Calculator", "href": "#" }
            ]
        },
        {
            "title": "Sequences calculators",
            "icon": GitCommitHorizontal,
            "calculators": [
                { "name": "Arithmetic Sequence Calculator", "href": "#" },
                { "name": "Collatz Conjecture Calculator", "href": "#" },
                { "name": "Convolution Calculator", "href": "#" },
                { "name": "Fibonacci Calculator", "href": "#" },
                { "name": "Geometric Sequence Calculator", "href": "#" },
                { "name": "Harmonic Number Calculator", "href": "#" },
                { "name": "Lagrange Error Bound Calculator", "href": "#" },
                { "name": "Pascal's Triangle Calculator", "href": "#" },
                { "name": "Sequence Calculator", "href": "#" },
                { "name": "Sum of a Linear Number Sequence Calculator", "href": "#" },
                { "name": "Sum of Series Calculator", "href": "#" }
            ]
        },
        {
            "title": "Exponents and logarithms calculators",
            "icon": FunctionSquare,
            "calculators": [
                { "name": "Antilog Calculator – Antilogarithm", "href": "#" },
                { "name": "Change of Base Formula Calculator", "href": "#" },
                { "name": "Condense Logarithms Calculator", "href": "#" },
                { "name": "Dividing Exponents Calculator", "href": "#" },
                { "name": "Dividing Radicals Calculator", "href": "#" },
                { "name": "e Calculator | eˣ | e Raised to Power of x", "href": "#" },
                { "name": "Expanding Logarithms Calculator", "href": "#" },
                { "name": "Exponent Calculator", "href": "#" },
                { "name": "Exponential Form Calculator", "href": "#" },
                { "name": "Exponential Function Calculator", "href": "#" },
                { "name": "Exponential Growth Calculator", "href": "#" },
                { "name": "Log Calculator (Logarithm)", "href": "#" },
                { "name": "Log Base 2 Calculator", "href": "#" },
                { "name": "Multiplying Exponents Calculator", "href": "#" },
                { "name": "Multiplying Radicals Calculator", "href": "#" },
                { "name": "Natural Log Calculator", "href": "#" },
                { "name": "Negative Log Calculator", "href": "#" },
                { "name": "Power of a Power Calculator", "href": "#" }
            ]
        },
        {
            "title": "Binary calculators",
            "icon": Binary,
            "calculators": [
                { "name": "AND Calculator", "href": "#" },
                { "name": "Binary Addition Calculator", "href": "#" },
                { "name": "Binary Division Calculator", "href": "#" },
                { "name": "Binary Fraction Converter", "href": "#" },
                { "name": "Binary Multiplication Calculator", "href": "#" },
                { "name": "Binary Calculator", "href": "#" },
                { "name": "Binary Subtraction Calculator", "href": "#" },
                { "name": "Bit Shift Calculator", "href": "#" },
                { "name": "Bitwise Calculator", "href": "#" },
                { "name": "NOR Calculator", "href": "#" },
                { "name": "One's Complement Calculator", "href": "#" },
                { "name": "OR Calculator", "href": "#" },
                { "name": "Two's Complement Calculator", "href": "#" },
                { "name": "XOR Calculator", "href": "#" }
            ]
        },
        {
            "title": "Other calculators",
            "icon": Lightbulb,
            "calculators": [
                { "name": "Babylonian Numbers Converter", "href": "#" },
                { "name": "Cyclomatic Complexity Calculator", "href": "#" },
                { "name": "Galileo's Paradox of Infinity Calculator", "href": "#" },
                { "name": "Hilbert's Hotel Paradox Calculator", "href": "#" },
                { "name": "Involute Function Calculator", "href": "#" },
                { "name": "LFSR Calculator", "href": "#" },
                { "name": "Luhn Algorithm Calculator", "href": "#" },
                { "name": "Mayan Numerals Converter", "href": "#" },
                { "name": "Miracle Calculator", "href": "#" },
                { "name": "Potato Calculator", "href": "#" },
                { "name": "Prisoner's Dilemma Calculator", "href": "#" },
                { "name": "Queueing Theory Calculator", "href": "#" },
                { "name": "RSA Calculator", "href": "#" },
                { "name": "Ugly Duckling Theorem Calculator", "href": "#" }
            ]
        }
    ]
}
